name: "Test"
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        # This input is unused, but required.
        name: my-cache
        # Skip pushing to Cachix. We only care about GitHub's cache.
        skipPush: true
        # Same as before.
        skipAddingSubstituter: true


    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Fetch nix packages
      run: "nix develop --command true"

    - name: Clojure tests
      run: "nix develop --command ./bin/test"
